// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPe828nEqxDDdESXkZOm7XeWNYwpkgx7M',
    appId: '1:30785568935:web:f92d827dfc04b42813db82',
    messagingSenderId: '30785568935',
    projectId: 'tobetopair',
    authDomain: 'tobetopair.firebaseapp.com',
    storageBucket: 'tobetopair.appspot.com',
    measurementId: 'G-Q23QMMETD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSMKelu2Yvo8hdluJDgkMlGNGU0tN1JY',
    appId: '1:30785568935:android:15a185ea7595e54113db82',
    messagingSenderId: '30785568935',
    projectId: 'tobetopair',
    storageBucket: 'tobetopair.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJsbscseYquMJJZ3IKIpD4hbptvvGD4k',
    appId: '1:30785568935:ios:dcb44bb5cf1ab02813db82',
    messagingSenderId: '30785568935',
    projectId: 'tobetopair',
    storageBucket: 'tobetopair.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhJsbscseYquMJJZ3IKIpD4hbptvvGD4k',
    appId: '1:30785568935:ios:14711c61f1483bf413db82',
    messagingSenderId: '30785568935',
    projectId: 'tobetopair',
    storageBucket: 'tobetopair.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
